version: "3.8"
services:
  db:
    image: postgres
    container_name: btf-db
    restart: always
    environment:
      POSTGRES_PASSWORD: "${postgres_pass}"
      POSTGRES_USER: "${postgres_user}"
      POSTGRES_DB: "${postgres_db}"
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    container_name: btf-adminer-container
    restart: always
    ports:
      - 8080:8080
volumes:
  my_db_files: